### ISSUE TITLE
Binary operator overloads missing required parentheses

### ISSUE THREAD

**Issue by nathan-alden-sr** [dotnet/ClangSharp#135]
From `winnt.h`:
```cs
public static JOB_OBJECT_NET_RATE_CONTROL_FLAGS Or(JOB_OBJECT_NET_RATE_CONTROL_FLAGS a, JOB_OBJECT_NET_RATE_CONTROL_FLAGS b)
{
    return (JOB_OBJECT_NET_RATE_CONTROL_FLAGS)((int)a) | ((int)b);
}
```
This is causing the following compiler error due to missing parentheses around the binary operator and its operands:
```
CS0019	Operator '|' cannot be applied to operands of type 'JOB_OBJECT_NET_RATE_CONTROL_FLAGS' and 'int'
```

**Comment by tannergooding** [comment]
The current codegen works as expected for `DEFINE_ENUM_FLAG_OPERATORS(ENUMTYPE)`.

It's worth noting that enum operators are something that you likely want to exclude by default since these "just work" for C#. There is a built-in config switch for doing so in the form of `-c exclude-enum-operators`
