### ISSUE TITLE
DivideByZeroException in GetTypeSize

### ISSUE THREAD

**Issue by andrew-boyarshin** [dotnet/ClangSharp#224]
```csharp
public override Task NestedDeclarationTest()
{
    var inputContents = @"struct CustomNativeNew {};

struct CustomNativeNewNested
{
    CustomNativeNew Nested;
};
";

    var expectedOutputContents = @"namespace ClangSharp.Test
{
    public partial struct CustomNativeNew
    {
    }

    public partial struct CustomNativeNewNested
    {
        public CustomNativeNew Nested;
    }
}
";

    return ValidateGeneratedCSharpLatestWindowsBindingsAsync(inputContents, expectedOutputContents);
}
```

Found after fixing #223 (actually, first uncovered when working on next-generation SharpGen based on ClangSharp).

[Test origin](https://github.com/SharpGenTools/SharpGenTools/blob/85696627830af1a8cf00918642769087b27abb36/SdkTests/Native/Struct/StructNative.h#L74-L78).

![image](https://user-images.githubusercontent.com/3063662/112846647-78402880-90d0-11eb-9a79-c1686d9f3b4b.png)
![image](https://user-images.githubusercontent.com/3063662/112846655-7aa28280-90d0-11eb-9d74-a4d9388c34cb.png)

**Comment by tannergooding** [comment]
This likely means that an unsupported type declaration was also encountered and the size/alignment for it was not changed from the default.

The else block that adds the diagnostic should likely set the alignment to the default alignment (`4/8`) if nothing else has been set to avoid this issue.

**Comment by tannergooding** [comment]
This one isn't repro'ing anymore. I believe I fixed it a while back when I adjusted the handling to use `-1` as the default.
