### ISSUE TITLE
Add option to use relative paths for NativeTypeName

### ISSUE THREAD

**Issue by thhous-msft** [dotnet/ClangSharp#259]
Right now, a full path to each header file is used for NativeTypeName in generated files. This makes it so generating in CI or across different dev systems has different paths. Instead, an option to allow relative paths to be used for this would be very helpful for reproducible generations.

**Comment by tannergooding** [comment]
What would this path be relative to? A separate/explicitly stated option?

**Comment by thhous-msft** [comment]
Likely, yeah. I'm generating into a path in the source tree, so a relative path in the same source tree is what I would want.
