### ISSUE TITLE
Could not download ClangSharpPInvokeGenerator v13 as global tools

### ISSUE THREAD

**Issue by yamachu** [dotnet/ClangSharp#294]
Currently, the README says to install v13 global tools, but NuGet only has v12 uploaded.
https://www.nuget.org/packages/ClangSharpPInvokeGenerator/12.0.0-beta2

If there is a NuGet source to download v13, please make an announcement about it.

**Comment by uberhalit** [comment]
Seems like they pulled it from nuget. Waiting for a new release.

**Comment by tannergooding** [comment]
The ClangSharpPInvokeGenerator hasn't been published yet. We're in the process of moving over to the .NET Foundation and fixing some remaining scenarios before a new package for the tool gets published.

**Comment by tannergooding** [comment]
https://github.com/dotnet/ClangSharp/releases/tag/v13.0.0-beta1

https://www.nuget.org/packages/ClangSharp/13.0.0-beta1
https://www.nuget.org/packages/ClangSharp.Interop/13.0.0-beta1
https://www.nuget.org/packages/ClangSharp.PInvokeGenerator/13.0.0-beta1
https://www.nuget.org/packages/ClangSharpPInvokeGenerator/13.0.0-beta1
