### ISSUE TITLE
Allow configurable access modifier using star

### ISSUE THREAD

**Issue by ThomasGoulet73** [dotnet/ClangSharp#323]
Currently, `--with-access-specifier *=internal` does not seem to work and I think it would be useful when you want to generate internal bindings. Passing true as the fourth parameter in the call to `TryGetRemappedValue` here seems to fix this issue:
https://github.com/dotnet/ClangSharp/blob/82e67150780efe0b34441997ad77c94b847e18ce/sources/ClangSharp.PInvokeGenerator/PInvokeGenerator.cs#L1814

I'm not very familiar with this codebase so I'll let the maintainers decide if this is the right fix and I would be happy to submit a PR.

**Comment by tannergooding** [comment]
This was resolved with https://github.com/dotnet/ClangSharp/pull/359
