### ISSUE TITLE
Prebuilt libClangSharp.runtime for Apple Silicon (osx-arm64) would be nice

### ISSUE THREAD

**Issue by vvuk** [dotnet/ClangSharp#345]
Would be nice to have this, because otherwise you need to have the `osx-x64` runtime/SDK installed on a M1 mac.  (I can't actually find any info on if it's possible to have both `osx-arm64` and `osx-x64` installed before -- at the very least they fight over what architecture things like the `dotnet` tool itself are.)

Unfortunately there are no prebuilt binaries for clang for osx-arm64.

**Comment by tannergooding** [comment]
I hadn't done that yet since LLVM itself hadn't been providing stable binaries yet.

However, I can test this out the next time I regenerate the native bits.

**Comment by tannergooding** [comment]
Getting this built as part of v15.0.0. It should be up by end-of-day (assuming no issues are hit with building LLVM on my M1).

**Comment by tannergooding** [comment]
This is provided now: https://www.nuget.org/packages/libClangSharp.runtime.osx-arm64
