### ISSUE TITLE
__builtin_offsetof generates to Marshal.OffsetOf

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/ClangSharp#347]
Marshal.OffsetOf is both going to be slow, and potentially incorrect in some cases (Although I'm not sure the generator can generate these invalid cases). 

In newer versions of the windows sdk, FIELD_OFFSET changed from 

```
#define FIELD_OFFSET(type, field)    ((LONG)(LONG_PTR)&(((type *)0)->field))
```

to
```
#define FIELD_OFFSET(type, field)    ((LONG)__builtin_offsetof(type, field))
```
which causes any macro using FIELD_OFFSET to now be generated with Marshal.OffsetOf

**Comment by tannergooding** [comment]
This is expected. The `(nuint)&(((T*)0)->field)` trick doesn't work in .NET and will generate a NRE due to the dereference required to get the field.

The next closest thing that .NET could do that isn't `Marshal.OffsetOf` is:
```csharp
Unsafe.SkipInit(out T tmp);
return ((nuint)&tmp.field - (nuint)&tmp))
```

But this has its own complications.
