### ISSUE TITLE
CX_CharacterKind.CX_CLK_Ascii literal breaks GUID

### ISSUE THREAD

**Issue by miloush** [dotnet/ClangSharp#349]
```c
inline constexpr GUID InterfaceGetIID(name*) noexcept { return GUID{ uuid }; }
DWRITE_BEGIN_INTERFACE(IDWriteFontFileLoader, "727cad4e-d6af-4c9e-8a08-d695b11caa49") : IUnknown
```

```C#
public static Guid InterfaceGetIID(IDWriteFontFileLoader* param0)
{
    return new Guid(new byte[] { 0x37, 0x32, 0x37, 0x63, 0x61, 0x64, 0x34, 0x65, 0x2D, 0x64, 0x36, 0x61, 0x66, 0x2D, 0x34, 0x63, 0x39, 0x65, 0x2D, 0x38, 0x61, 0x30, 0x38, 0x2D, 0x64, 0x36, 0x39, 0x35, 0x62, 0x31, 0x31, 0x63, 0x61, 0x61, 0x34, 0x39, 0x00 });
}
```

**Comment by tannergooding** [comment]
@miloush could you provide more context on this.

It looks like you've got an invalid declaration in the first place as `GUID { }` is going to expect a initializer list expression and not an ASCII string.

Looking at `dwrite_core.h`, its not clear where the define is coming from or how it's being modified.

**Comment by tannergooding** [comment]
Closing this as its waiting on author feedback so a reliable repro can be created.

Please feel free to re-open if the necessary details can be provided.
