### ISSUE TITLE
Cannot marshal 'parameter #1': Pointers cannot reference marshaled structures. Use ByRef instead.

### ISSUE THREAD

**Issue by ujos** [dotnet/ClangSharp#350]
Cannot pass the structure via pointer if structure contains a `bool` variable. Code compiles but `MarshalDirectiveException` exception is thrown during runtime.

### Steps to reproduce
1. Download and extract [test.zip](https://github.com/dotnet/ClangSharp/files/8894311/test.zip)
2. Run `reproduce.cmd`

Expected that test.exe prints nothing. 

In fact the output is:

```txt
Unhandled Exception: System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #1': Pointers cannot reference marshaled structures.  Use ByRef instead.
   at TestLib.DLL.foo(X* x)
   at Program.<Main>$(String[] args)
```

In case if I replace pointer with `ref`, the code works.

### Version

```txt
 (master) test $ ClangSharpPInvokeGenerator --version
ClangSharp P/Invoke Binding Generator version 14.0.0
  clang version 14.0.0
  clangsharp version 14.0.0
```

### Archive content

```cpp
// test_lib.h

#include <stdbool.h>

#ifdef __cplusplus
extern "C"
{
#endif

struct X 
{
    bool Flag;
};

void __declspec(dllexport) foo(struct X const* x);

#ifdef __cplusplus
}
#endif
```

```cpp
// test_lib.cpp

#include "test_lib.h"

void foo(X const*)
{
}
```

Following is config file for `ClangSharpPInvokeGenerator`

```txt
--file
test_lib.h

--namespace
TestLib

--headerFile
pinvoke-header.txt

--output
test_lib.cs

--language
c++

--methodClassName
DLL

--libraryPath
test_lib.dll

--config
compatible-codegen
```

Following is a C# test program:

```csharp
using ClangSharp.Interop;

unsafe
{
    var x = new TestLib.X();

    TestLib.DLL.foo(&x);
}
```

**Comment by tannergooding** [comment]
At first glance this looks like a bug in ClangSharp. `bool` on the native side should be normalized to `byte` on the C# side due to the ABI incompatibility.

For .NET 7 and later, `bool` could be used if the user opts into `[assembly: System.Runtime.CompilerServices.DisableRuntimeMarshalling]`, but that's not a feature ClangSharp supports yet.

I thought I had tests covering this scenario, but I'll be able to take a look in a day or two and confirm.

**Comment by ujos** [comment]
It seems you handle the `bool` type in the function declaration but not in the structure declaration.
