### ISSUE TITLE
Where is gui generator with p/invoke to cs file?

### ISSUE THREAD

**Issue by DeafMan1983** [dotnet/ClangSharp#351]
Hello Tanner , I would like to know since I read CppSharp that's correct you mean p/invoke generation editor can generate header files to public methods into dllimport, definitions and structures and writes a generated file.cs if I understand correctly.  I really want to know how do I use ClangSharp. But I am new for generation.  I thought you can conjure finished structures, definitions and methods. Right? Welcome witch Tanner on our earth!

**Comment by tannergooding** [comment]
The basic instructions for using ClangSharp are here: https://github.com/dotnet/ClangSharp#generating-bindings There is not any public facing UI for it today, its all command line support.

As per the instructions above, https://github.com/dotnet/ClangSharp/blob/main/sources/ClangSharpPInvokeGenerator/Properties/GenerateClang.rsp is an example of how `ClangSharp` itself is generated.

A more complex example covering D3D12 is here: https://github.com/terrafx/terrafx.interop.windows/blob/main/generation/DirectX/d3d12/d3d12/generate.rsp. Neighboring files also cover a large portion of the Windows SDK.

https://github.com/terrafx/terrafx.interop.xlib/blob/main/generation/Xlib/X11/X/generate.rsp and neighboring files covers Xlib
https://github.com/terrafx/terrafx.interop.vulkan/blob/main/generation/Vulkan/vulkan/vulkan/generate.rsp and neighboring files covers Vulkan

**Comment by DeafMan1983** [comment]
Hi Tanner, thanks for explanation!
I have tried but ClanSharpPInvokeGenerator throws exceptions and errors cause DLLNotFOUNDEXCEPTION
```
ClangSharpPInvokeGenerator @generation.rsp
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: Unable to load shared library 'libClangSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibClangSharp: cannot open shared object file: No such file or directory
   at ClangSharp.Interop.clangsharp.getVersion()
   at ClangSharp.PInvokeGenerator..ctor(PInvokeGeneratorConfiguration config, Func`2 outputStreamFactory) in /_/sources/ClangSharp.PInvokeGenerator/PInvokeGenerator.cs:line 80
   at ClangSharp.Program.Run(InvocationContext context) in /_/sources/ClangSharpPInvokeGenerator/Program.cs:line 562
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

I already installed libclang-14, libclang-14-dev and libclang1 and more and I use Ubuntu 22.04 
LIBRARY_PATH uses /lib/x86_64-linux-gnu because Ubuntu 22.04 has new changes since Ubuntu 21.04 uses /usr/lib/x86_64-linux-gnu

Thanks!

**Comment by DeafMan1983** [comment]
Hey Tanner, 

I found solution.

for Linux: It looks wrong because I made easy
```
git clone https://github.com/dotnet/clangsharp
cd clangsharp
mkdir artifacts/bin/native
cd artifacts/bin/native
cmake -DPATH_TO_LLVM=/usr/lib/llvm/14/ ../../..
make
```
with
```
git clone https://github.com/dotnet/clangsharp
cd clangsharp
mkdir -p artifacts/bin/native
cd artifacts/bin/native
cmake -DPATH_TO_LLVM=/usr/lib/llvm-14/ ../../..
make -j32
```

Copy 2 so files and past to lib/x86_64-linux-gnu:
```
sudo cp -p ~/clangsharp/artifacts/bin/native/lib/libClangSharp.so ~/clangsharp/artifacts/bin/native/lib/libClangSharp.so.14.0.0 /lib/x86_64-linux-gnu
```
Screenshot:
![image](https://user-images.githubusercontent.com/57066679/173971523-a4c8e9de-4d43-4863-bbcc-2fb7cf2b6f69.png)
Download libClangSharp.so for Ubuntu 22.04 x64 only
[libClangSharp.zip](https://github.com/dotnet/ClangSharp/files/8914877/libClangSharp.zip)

And try with ClangSharpPInvokeGenerator with version and it works fine. :D 

Because errors from Ubuntu 20.04 libClangSharp.so can't work with latest version of Ubuntu cause Kernel version very latest and has higher level.

It works fine now. I would like to close issue :)

**Comment by DeafMan1983** [comment]
Wow I have tried to use Generator create new file and writes DLLImport lines. But it seems can't create can't write file 

I have tried generated Xlib.cs with DLLImport pinvokes 

I have changed Xlib.cs with _Xlib.cs then I type with ClangSharpPInvokeGenerator @generate.rsp then result is:` Processing 'Xlib-X.h'`

I have tested without directory sources and it looks output with generated *.cs files

**Comment by tannergooding** [comment]
@DeafMan1983 could you clarify what the current issue is?

It looks like you might be in `-config single-file` rather than `-config multi-file` mode.

**Comment by kkukshtel** [comment]
I'm running into this DLL missing issue as well (on MacOS):

```
Unhandled exception: System.DllNotFoundException: Unable to load shared library 'libclang' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibclang, 0x0001): tried: 'liblibclang' (no such file), '/usr/local/lib/liblibclang' (no such file), '/usr/lib/liblibclang' (no such file), '/Users/kyle/Workspace/ClangSharp/artifacts/bin/sources/ClangSharpPInvokeGenerator/Release/net6.0/liblibclang' (no such file)
```

I've got libClangSharp extracted from the NuGet package here: https://www.nuget.org/packages/libClangSharp.runtime.osx-x64/14.0.0-beta1
And have placed it next to the (built from source) ClangSharpPInvokeGenerator. 

I've tried symlinking in to Clang on the system via xcode's path and the usr/bin/ clang version to no avail. Not totally sure what's missing here, would love any additional help.

**Comment by DeafMan1983** [comment]
Okay thanks for closing!
