### ISSUE TITLE
Where is stable version of ClangSharp?

### ISSUE THREAD

**Issue by kant2002** [dotnet/ClangSharp#354]
I found that it's wierd that at version 14.x ClangSharp still does not have any `stable` version on Nuget. I **highly** doubt that this project **that much** immature. Even if it is not latest maybe worth having stable version, and if somebody need prerelease it can install it .

**Comment by tannergooding** [comment]
The project is still pending signing certificate support from the .NET Foundation before stable binaries get released.

**Comment by kant2002** [comment]
Now I realize that it is about 6 month from time when ClangSharp join Dotnet Foundation, is procurement of certificates take **that long** there?

**Comment by tannergooding** [comment]
Signing has happened now and v14.0.0-rc1 is the first available to be signed.

Few more tweaks and validation steps to happen and hopefully I can get v14.0.0 stable out around mid September.

**Comment by tannergooding** [comment]
It's mid September and I am indeed pushing out a stable release today. Notably It's going to be v15.0.0, rather than v14.0.0.

**Comment by tannergooding** [comment]
Resolved with https://github.com/dotnet/ClangSharp/releases/tag/v15.0.0
