### ISSUE TITLE
Ubuntu 22.04 Support

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/ClangSharp#364]
Ubuntu 21.10 appears to be the latest supported. Would be great to get 22.04 support.
Can't really tell whether support is an upstream thing or how this works, just wanted to bring it up.
Not really important for me, just noticed cause GitHub Actions has Ubuntu 22.04 runners.

**Comment by tannergooding** [comment]
This now exists for v15.0.0 which was merged in https://github.com/dotnet/ClangSharp/pull/386

Have a couple more issues to resolve and then new packages should be up on NuGet. Nightly packages are already available.
