### ISSUE TITLE
ACTIVATION_CONTEXT_COMPATIBILITY_INFORMATION not getting marked as unsafe when it contains a pointer

### ISSUE THREAD

**Issue by sotteson1** [dotnet/ClangSharp#366]
winnt.h:
```C
typedef struct _ACTIVATION_CONTEXT_COMPATIBILITY_INFORMATION {
    DWORD ElementCount;
    COMPATIBILITY_CONTEXT_ELEMENT Elements[];
} ACTIVATION_CONTEXT_COMPATIBILITY_INFORMATION, * PACTIVATION_CONTEXT_COMPATIBILITY_INFORMATION;
```

Scanned output:
```C#
    public partial struct ACTIVATION_CONTEXT_COMPATIBILITY_INFORMATION
    {
        [NativeTypeName("DWORD")]
        public uint ElementCount;

        [NativeTypeName("COMPATIBILITY_CONTEXT_ELEMENT[]")]
        public COMPATIBILITY_CONTEXT_ELEMENT* Elements;
    }
```

This was using 14.0.0-beta2, which I'm trying to upgrade to in the Win32Metadata project. The previous version I was using omitted the * but I was able to turn it into an array by looking at the NativeTypeName attribute.

**Comment by tannergooding** [comment]
Reopening. The issue isn't that `unsafe` is missing but this being treated as a pointer at all.

C incomplete arrays are the "same" as zero sized arrays (that is `COMPATIBILITY_CONTEXT_ELEMENT Elements[]` is the same as `COMPATIBILITY_CONTEXT_ELEMENT Elements[0]`).

This has interesting behaviors where-as it is functionally:
```csharp
    public partial struct ACTIVATION_CONTEXT_COMPATIBILITY_INFORMATION
    {
        [NativeTypeName("DWORD")]
        public uint ElementCount;

        [NativeTypeName("COMPATIBILITY_CONTEXT_ELEMENT[]")]
        public COMPATIBILITY_CONTEXT_ELEMENT Elements;
    }
```

And where `Elements` impacts the alignment/packing of the struct, but where `sizeof` is not supposed to include the size of the single `Elements` entry.

**Comment by tannergooding** [comment]
Much like many structs that have `0/1` fixed-sized buffers, these "must" be the last element and the overall struct must always be accessed/passed by reference.
