### ISSUE TITLE
static const strings not scraped correctly

### ISSUE THREAD

**Issue by sotteson1** [dotnet/ClangSharp#369]
````C
//Type: LPCWSTR, WMDM_TAG_DATATYPE: WMDM_TYPE_STRING
static const WCHAR *g_wszWMDMFileName = L"WMDM/FileName";
````
Version 11:
````C#
    public const string g_wszWMDMFileName = "WMDM/FileName";
````

Version 14:
````C#
    public static string g_wszWMDMFileName = "WMDM/FileName";
````

**Comment by tannergooding** [comment]
@sotteson1, the v14.0 behavior is technically correct here.

`const wchar_t*` (or `wchar_t const*`) means that mutating the contents is illegal, but mutating the variable is legal:
```cpp
const wchar_t* a = ...;

a = L"x";      // legal
a[0] = L'x';   // illegal
```

`wchar_t* const` means that mutating the contents is legal, but mutating the variable is illegal:
```cpp
wchar_t* const a = ...;

a = L"x";      // illegal
a[0] = L'x';   // legal
```

`const wchar_t* const` (or `wchar_t const* const`) means that mutating both the contents and variable is illegal:

**Comment by tannergooding** [comment]
The many `g_wszWMDM*` constants defined in `mdwmdm.h` are all allotted storage slots and can be mutated by regular C code.

The following exhibits that behavior:
```csharp
#include <iostream>
#include <Windows.h>
#include <mswmdm.h>

int main()
{
    std::cout << g_wszWMDMFileName << std::endl;

    g_wszWMDMFileName = L"Test";

    std::cout << g_wszWMDMFileName << std::endl;
}
```

**Comment by tannergooding** [comment]
PR adds tests explicitly covering this behavior, but as is the current codegen is "correct" for Windows `const wchar_t* x = L"...";`

There were a couple edge cases that needed similar handling for UTF-8 and UTF-32 string literals.
