### ISSUE TITLE
Help for all double dash things.

### ISSUE THREAD

**Issue by coolcatcoder** [dotnet/ClangSharp#380]
A small suggestion. It would be very useful to have the ability to get help with any double dash things (I don't know their name, sorry lol). For example you can get help with **`--config`** using **`-c help`**. It would be nice to have this for all, as aside from trial and error it can be hard to understand how to use certain double dash things, for example when looking at **`--with-librarypath`** it is unclear whether it is for saying which header uses which dll, or if it is instead for each method.

**Comment by tannergooding** [comment]
Do you mean an example syntax like `method=library`

The current help output is:
> -wlb, --with-librarypath <with-librarypath>                A library path to be used for the given declaration during binding generation. []

**Comment by tannergooding** [comment]
Most of the help syntax is of the form `name=value`

Where name can be the `partial` or `qualified-name` of the members a `--with-*` is relevant to.

In the case of `--with-librarypath`, this is used for the `DllImport("value")` for a given method and so you can use `Foo` or `Foo(int):void` or if its a qualified C++ declaration (like under a namespace or in a class), `Parent.Foo`/`Parent.Foo(int):void` work as well. You can also use `Parent::Foo` if you're wanting to match the C++ separator syntax.

Other `--with-*` options may work on types or something else instead. I've tried to clarify the declaration kind where that's relevant (such as `enum declaration` or `type declaration`).

**Comment by coolcatcoder** [comment]
Oh ok cool, that makes sense!
