### ISSUE TITLE
Unable to run ClangSharpPInvokeGenerator

### ISSUE THREAD

**Issue by Beyley** [dotnet/ClangSharp#381]
any command i try to run with the app produces this error
![image](https://user-images.githubusercontent.com/34501060/188254354-3fb37705-3b8c-4a6e-beec-af5620db9fc1.png)

```
┌[beyley☮wacky]-(~/libinput/include/linux/linux)-[git://master ✗]-
└> clang --version
clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by tannergooding** [comment]
Could you provide more information about the terminal you're using?

This seems like a bug there and that its trying to automagically resolve and register command line options for `libClangSharp.so` which conflicts with any options that may be registered by `libClang.so`

`static-func-full-module-prefix` is an internal (non public) Clang/LLVM command line option and not some part of ClangSharp itself.

**Comment by tannergooding** [comment]
(Of course this could be a compilation issue or something trivial to resolve on my end, so details would help resolve this 😄)

**Comment by tannergooding** [comment]
Please feel free to re-open with more details if needed
