### ISSUE TITLE
Allocate blittable object on stack memory

### ISSUE THREAD

**Issue by kgb7711** [dotnet/ClangSharp#399]
In a game loop, if we want to display fps, the game app will generate tons of string instances, thus has a huge impact on performance.
If we can allocate blittable object on stack, the impact will be greatly alleviated. We need the following:
char* ptr = stackalloc $"The frame per second is :{fps}."; //Because string is an array of chars,it is blittable

**Comment by tannergooding** [comment]
This is the wrong repo for such an issue. You likely want `dotnet/runtime` and/or `dotnet/csharplang`.
