### ISSUE TITLE
Add support for CLong and CULong

### ISSUE THREAD

**Issue by nazar554** [dotnet/ClangSharp#400]
Currently long is either an int or nint (depending on windows-types or unix-types). Can use CLong for latest codegen with .NET6

**Comment by tannergooding** [comment]
This is a complicated change to make for many reasons, most particularly due to how Clang can only parse for one platform.

I suggest you add a `--remap long=CLong` and `--with-namespace CLong=System.Runtime.InteropServices` if it is appropriate for your particular generation scenario
