### ISSUE TITLE
Static Linking Library?

### ISSUE THREAD

**Issue by Tyrion3000** [dotnet/ClangSharp#402]
Is it possible to be able to use clangsharp/llvmsharp to use static libraries (.lib) to generate p/invoke bindings for C++ code or is that not feasible and clangsharp is only usable for C projects? I apologize for opening this issue but I did not know any other way to ask this way or contact the developers.

**Comment by Perksey** [comment]
You need the C headers to generate the bindings, once you have the bindings you can configure NativeAOT to statically link your libs and resolve the generated P/Invokes.
