### ISSUE TITLE
Generic linux-x64 native libraries can't be loaded on Arch Linux, ubuntu.22.04-x64 works

### ISSUE THREAD

**Issue by copygirl** [dotnet/ClangSharp#412]
I made this issue partially for others to see, as I've found a solution that works for me and I'd like to help others in need.

First of all, without providing a `RuntimeIdentifier`, no native libraries ended up being included. This might be because Arch's default runtime identifier is `arch-x64`. When specifying `linux-x64` explicitly, the library fails to load, but I am greeted with a "Failed to resolve libClang or libClangSharp." message, which made me incorrectly think it simply *could not find* the library.

In the end, I managed to resolve the issue on my end by using the libraries targeting Ubuntu. My `.csproj` includes this:

```xml
  <PropertyGroup>
    <RuntimeIdentifier>ubuntu.22.04-x64</RuntimeIdentifier>
    <!-- Place output files directly in "bin/Debug/<framework>/" instead of "ubuntu.22.04-x64/" subfolder. -->
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClangSharp" Version="15.0.2" />
    <!-- It looks like no other packages need to be referenced explicitly. -->
  </ItemGroup>
```

Having struggled around with this on and off for days, I hope the usage experience can improve in the future.

**Comment by tannergooding** [comment]
This is an issue that stems from NuGet, Linux, and Clang in general.

On the NuGet side, there is no easy way to package native dependencies nor a way to have them correctly restore across all possible RIDs.

On the Linux side, there are many different distros and distro versions. Some of these are loosely compatible, but for the most part no two distros or distro versions are fully compatible. This can result in libraries/apps that have to be built "per distro/version"

On the Clang side, it is such an app that depends on many lower level APIs and where the breaks across distro versions become much more visible. Unlike .NET which tries very hard to be broadly portable, Clang is very much not and has a plethora of different builds.

If `linux-x64` were made to be `ubuntu22.04`, then it would break platforms with a lower libc (and other library) versions, like most RHEL/SuSe releases, etc.

**Comment by tannergooding** [comment]
There are actually a few other existing issues covering the same problem where I've described this in more, less, or similar detail.

I would definitely fix this if I could and I have opened issues against the relevant places where possible already.

**Comment by copygirl** [comment]
> There are actually a few other existing issues covering the same problem where I've described this in more, less, or similar detail.

I've read a couple of them, and unfortunately none have lead me to this particular solution. Some where about using the PInvokeGenerator as a dotnet tool, others had some strange recommendations, and maybe all were about versions before 15, which was said to have resolved some things?

Part of this issue is also about how, once I technically did the right thing by supplying a working `RuntimeIdentifier`, I was lead astray by the error message leading me to believe the library file was still not being found. Though if I understand native library loading and also remember correctly, it might not be possible to differentiate "not found" vs "problem while loading"?

**Comment by tannergooding** [comment]
The v16.0.0 binaries have been uploaded and had the most problematic dependencies removed (terminfo, zlib, zstd) or statically linked (libstdc++).

This should provide a smoother experience for most Linux distro's, provided they are on `glibc 2.27` or later
