### ISSUE TITLE
Read behaviour for signed bitfields is inconsistent with Clang, MSVC and GCC

### ISSUE THREAD

**Issue by DaZombieKiller** [dotnet/ClangSharp#415]
When generating an interop structure for the following type:
```cpp
struct PackedVertex
{
    union
    {
        int i;
        struct
        {
            int x : 11;
            int y : 11;
            int z : 10;
        };
    };
};
```
`ClangSharpPInvokeGenerator` produces accessors like the following:
```cs
[NativeTypeName("int : 11")]
public int x
{
    get
    {
        return _bitfield & 0x7FF;
    }

    set
    {
        _bitfield = (_bitfield & ~0x7FF) | (value & 0x7FF);
    }
}
```
Which does not appear to handle the sign of each component properly.

Setting `i` to `0xFB3E7064` should produce `100, -50, -20` for `x, y, z`, but [with the currently generated code, it produces `100, 1998, 1004`](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIgBgAIiyA6AJXwwEsBbGZgSTwYYUCAAcAyiIBunMDADOAbmrUACgEMwAaxgATAGojhCetPoBeenhgB3ABQBKFVWnNOl+vjAALGDv17e04hR1oEADEAIQBmAFEAdlpUZ2omAE57ABIAIgBvNwQAXzR6AuYATxKytwAvIpzUqjSY+jENKC4NABt6BQxcMAx6TQDDYxgEajzqejnGVoB9AEE8CDwK7ggcBUWYRcWAVTxOdfpV9c3t5VUqeYX6WAAzehDhzln5mbv7+YBzGAYT6/MrAkHzIgJR4wF4AWRgWygFVhHQUPh6zAA4oDWDCRDA8PJ7PDEcjUejuswAMKwDTCCTtPD2Z7nNYbLY7dylMiOJrg+hFMGC5o/OZEVpvehTUWgmX3AFAuVfMH8yGsy4chTMC7s67MBAufnClXzBSAk1zb78+46q6c22a/WeaQ9HAwQ3g4X3Y0y8WvIT0Cpgq3ghUW2XWiFQh16mOcioekE+/lmxX8kORuNarOVZ2u93hr3zZMQiUB2rB8NhpWW8P3NU5nO1RO/Esg1PhjPWxtsu1a2p57pulveoW3e4AbQkAxwQwAMhoKtsMPYF0ucBgANIhPTMOIIMTdOScDCOAC6YL97U6nB6fRnQ3oK17mr2B2OpzwlZr9AnEU4MDdHoADyTxPKm9i0Oe4Z+pKnAuOGf4AUBoHgYCkHQT+frPhq1xvos06DMMWYIVhrTXl0vT9ERT5ZvhhGzmm4JdqqZbDIswAnk8yF6KRkZimxUp1sqP78tW/G/CxElRk+nEYNxgF6PQABk9DhAkEQRCO/FttJHaicxwmRhxXE8Z49gmfJZmqQAfupmmOPQBD0PYLpDjAKlqQgGkRHy0lzEWka6ax/rDEGBm1hFvzif5EaxfWUIWXJClAfQAB8aX0GQPKefZWlGa246xfp8VSf5lkpUpVhJaZimeTZkHeZp9AADwtVlPKOc5QRuW6uVNb5rXtdlfn+YF1rBeCsHlgVZXWjF/lzRJao1VZdUZfQJAkI5qnhDEmnaUFRX+SVsVLfxFVmdVl11bZjX7REQ2bdtXUua5+b9Q9jltc9o3SeNRqFmOVDCkAA===). If the code for the getters are tweaked to match the [assembly generated by Clang and MSVC](https://godbolt.org/z/oKcPWf4zW), then the [results are correct](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIgBgAIiyA6AJXwwEsBbGZgSTwYYUCAAcAyiIBunMDADOAbmrUACgEMwAaxgATAGojhCetPoBeenhgB3ABQBKFVWnNOl+vjAALGDv17e04hR1oEADEAIQBmAFEAdlpUZ2omAE57ABIAIgBvNwQAXzR6AuYATxKytwAvIpzUqjSY+jENKC4NABt6BQxcMAx6TQDDYxgEajzqejnGVoB9AEE8CDwK7ggcBUWYRcWAVTxOdfpV9c3t5VUqeYX6WAAzehDhzln5mbv7+YBzGAYT6/MrAkHzIgJR4wF4AWRgWygFVhHQUPh6zAA4oDWDCRDA8PJ7PDEcjUejuswAMKwDTCCTtPD2Z7nNYbLY7dylMiOJrg+hFMGC5o/OZEVpvehTUWgmX3AFAuVfMH8yGsy4chTMC7s67MBAufnClXzBSAk1zb78+46q6c22a/WeaQ9HAwQ3g4X3Y0y8WvIT0Cpgq3ghUW2XWiFQh16mOcioekE+/lmxX8kORuNarOVZ2u93hr3zZMQiUB2rB8NhpWW8P3NU5nO1RO/Esg1PhjPWxtsu1a2p57pulveoW3e4AbQkAxwQwAMhoKtsMPYF0ucBgANIhPTMOIIMTdOScDCOAC6YL97U6nB6fRnQ3oK17mr2B2OpzwlZr9AnEU4MDdHoADyTxPKm9i0Oe4Z+pKnAuOGf4AUBoHgYCkHQT+frPhq1xvos06DMMWYIVhrTXl0vT9ERT5ZvhhGzmm4JdqqZbDIswAnk8yF6KRkZimxUp1sqP78tW/G/CxElRvQ9gcVxPH0AAPEp9DkI49AAHyaWpZAjvxbbSR2onMcJkbyRg3GAXonhyZxlmKQAZPQAB+4QJBEEQaQQskukOMD0M57meXy0lzEWkaGax/rDEGJm1vFvziWFEYpfWUJ2Qp1nKapZBQVpOnkPpkXjilxlpVJYUWVZQG2dVTmuZBCAeREOX0GQPLebJ9h+W6gX0MFXltR1oVhRF1pReCsHlmZqVhclYWVdJar1dl2lqSQxUTbN9w7aa5qJfcS0SattVWJlDnZc5LlNTEnltSQJC8vQPlBL1AVBQgd1DSpG2jdJ41GoWY5UMKQA==).

**Comment by tannergooding** [comment]
This should be a simple fix. The general bitfield handling logic is in `VisitBitfieldDecl` here: https://github.com/dotnet/ClangSharp/blob/main/sources/ClangSharp.PInvokeGenerator/PInvokeGenerator.VisitDecl.cs#L2347

There is some upfront type checking and other handling and then the actual "code" emitted is handled a bit further down around here: https://github.com/dotnet/ClangSharp/blob/main/sources/ClangSharp.PInvokeGenerator/PInvokeGenerator.VisitDecl.cs#L2693

It's worth noting that the behavior of `int x : 11` in C is undefined. It could be `signed int` or `unsigned int`. In C++ it is well defined and treated as `signed int`
