### ISSUE TITLE
Checking if a file belongs in `--traversal` does not account for relative paths.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/ClangSharp#425]
[Repro (the same I had sent on Discord)](https://github.com/dotnet/ClangSharp/files/10872104/repro.zip)

The file `tiledb\api\c_api\vfs\vfs_api_external.h` has an `#include "..\context\context_api_external.h"` in it. All header files in the `tiledb` directory are passed to the tool via `--traverse`, but the tool sees the path `tiledb\api\c_api\vfs\..\context\context_api_external.h`, does not resolve the relative path and does not find it in the list, and skips `context_api_external.h`.

**Comment by tannergooding** [comment]
This should likely be a relatively easy fix.

I imagine we just need to extend [IsIncludedFileOrLocation](https://github.com/dotnet/ClangSharp/blob/main/sources/ClangSharp.PInvokeGenerator/PInvokeGenerator.cs#L4303) to also check `_config.TraversalNames.Contains(Path.GetFullPath(...))`

or alternatively to have [PInvokeGeneratorConfiguration](https://github.com/dotnet/ClangSharp/blob/main/sources/ClangSharp.PInvokeGenerator/PInvokeGeneratorConfiguration.cs) implicitly add the full path as an alternative to the set.

The latter is a bit more up-front cost but is overall more extensible and could be handled as part of the `AddRange` in the property `init`

**Comment by teo-tsirpanis** [comment]
Thanks for fixing it!
