### ISSUE TITLE
Support for new LibraryImport attribute

### ISSUE THREAD

**Issue by kkukshtel** [dotnet/ClangSharp#427]
Hello! Finally got this working and really love it. However I'd love to be able to use the new LibraryImport attribute instead of DLLImport (as well as its new parameters). I think exposing this as a configuration option if using preview/latest would make the most sense. Maybe being able to specify default params as well?

**Comment by tannergooding** [comment]
Today ClangSharp generates fully blittable bindings and so there is no benefit or need to using `LibraryImport`, it just causes a source generator to run which does "nothing" and generates an identical signature to what ClangSharp has already generated.

Supporting non-blittable bindings gets into the complexity I covered in https://github.com/dotnet/ClangSharp/issues/428#issuecomment-1454811249 and while it isn't impossible for such a thing to be added, it represents a great deal of complexity to the codebase and has been considered "out of scope" up until this point.

**Comment by kkukshtel** [comment]
Okay I see. I thought I had read in the release notes that it was faster, but you may be right that it only matters if the code uses marshalling.

**Comment by tannergooding** [comment]
Right, when marshalling is involved it is faster than using the runtime's "built-in" marshalling. But for blittable bindings its effectively a no-op and so just spends extra compile time cycles unnecessarily.

**Comment by kkukshtel** [comment]
Just based on my experience with this library I would say that if are doing intermediary marshaling on top of these bindings, you're better off just using LibraryImport on top of function bindings that are meant to be marshaled. Writing your own marshaling layer means you're effectively competing with the C# team on marshaling perf, and if it were me I'd assume the C# team can write better managed marshaling code than I could.
