### ISSUE TITLE
Add descriptive attributes to _bitfield properties that indicate the original name and size of the fields they represent

### ISSUE THREAD

**Issue by mikebattista** [dotnet/ClangSharp#435]
See https://github.com/microsoft/win32metadata/issues/1392#issuecomment-1477026622.

**Comment by mikebattista** [comment]
As shown in the example linked above, these private bitfield properties tend to represent more than one property. Each bitfield represents 32 bits and the helper functions you currently generate modify the corresponding bits in the bitfield.

How are you thinking of describing that here?

**Comment by tannergooding** [comment]
`[NativeBitfield("InstanceId", Offset = 0, Length = 24)]` and simply ensuring the attribute is `AllowMultiple = true`.

**Comment by mikebattista** [comment]
Perfect. Thanks.
