### ISSUE TITLE
[bug]The value of IsDeleted property in FunctionDecl is wrong

### ISSUE THREAD

**Issue by Liangjia0411** [dotnet/ClangSharp#447]
I use ClangSharp to analyze the Unreal Engine code, and found that the value of FunctionDecl::IsDeleted corresponding to the function marked as delete is 'false', and the value of FunctionDecl::IsDeleted corresponding to the function not marked as delete is 'true'. The sample code is as follows:
```c++
class FWindowsCriticalSection
{
public:
        //The value of FunctionDecl::IsDeleted corresponding to this method is 'false'
	FWindowsCriticalSection(const FWindowsCriticalSection&) = delete;

        //The value of FunctionDecl::IsDeleted corresponding to this method is 'false'
	FWindowsCriticalSection& operator=(const FWindowsCriticalSection&) = delete;

        //The value of FunctionDecl::IsDeleted corresponding to this method is 'true'
	FORCEINLINE FWindowsCriticalSection()
	{
	}
};
```

I have this problem in both v15.0.2 and v14.0.0-rc1 tags.

**Comment by tannergooding** [comment]
This has been resolved already in local builds, just haven't had time to get a new build up yet.
