### ISSUE TITLE
Support for disabled runtime marshalling

### ISSUE THREAD

**Issue by alexrp** [dotnet/ClangSharp#458]
https://learn.microsoft.com/en-us/dotnet/standard/native-interop/disabled-marshalling

There was some discussion on this topic in #428; I figured I'd open this issue to track support for this feature.

The `bool` issue in particular is one that I'm running into with a library that I'm generating bindings for. I am using `[assembly: DisableRuntimeMarshalling]` so it's a bit unfortunate that the P/Invoke signatures end up using `byte`. (Perhaps also worth noting that remapping with `--remap _Bool=bool` and/or `--remap bool=bool` as a hacky workaround isn't possible.)

**Comment by kkukshtel** [comment]
I ended up just doing a cast for the "bool" type at the calling location/handoff to managed code. I only ever touch the values once so it worked well enough for me.

**Comment by tannergooding** [comment]
Resolved in https://github.com/dotnet/ClangSharp/pull/480
