### ISSUE TITLE
Some things will missing when generate

### ISSUE THREAD

**Issue by MIRIMIRIM** [dotnet/ClangSharp#460]
I lost a part of it when using ClangSharpPInvokeGenerator convert c header, these are missing code
https://github.com/AmusementClub/vapoursynth-classic/blob/eb8f870aa34c22b9989f49adf9f6b854d5bb4900/include/VapourSynth4.h#L299-L312

I couldn’t find any relevant information about it, clangsharp version is 16.0.6.

**Comment by tannergooding** [comment]
What options are you specifying when trying to generate your code.

If you are using compatible-codegen, you should get some delegates emitted. If you are using latest or preview codegen, then these are handled as function pointers and there is no way to specify a public/reusable "type". Function pointers are always inlined at the use site instead.

**Comment by MIRIMIRIM** [comment]
Thank you for your reply

I am using latest-codegen, and I will continue to learn this part of the content
