### ISSUE TITLE
Test type is generated twice triggering compilation error

### ISSUE THREAD

**Issue by davidelettieri** [dotnet/ClangSharp#465]
I'm working on generating c# binding for tree-sitter. I got far enough and the work I've done is in this [repo](https://github.com/davidelettieri/treesitter-bindings).

However I have an issue were a test type is generated twice (snippet below). Right now I'm cleaning this manually either by removing the file or cleaning up one copy of the class. 

I'm including in the generation 2 files and I noticed that they both define `TSLanguage`. Could that be the problem? Notice the `ifndef` in the second snippet.

```
--file
tree-sitter/lib/include/tree_sitter/api.h
tree-sitter/lib/include/tree_sitter/parser.h
```

**api.h**
```c++
...
typedef struct TSLanguage TSLanguage;
...
```

**parser.h**
```c++
#ifndef TREE_SITTER_API_H_
typedef uint16_t TSSymbol;
typedef uint16_t TSFieldId;
typedef struct TSLanguage TSLanguage;
#endif
```

Is there a way to configure the `ClangSharpPInvokeGenerator` to handle this correctly?

## Duplicated class
```csharp
using System;
using System.Runtime.InteropServices;
using Xunit;

namespace TreeSitter.Bindings.UnitTests;

/// <summary>Provides validation of the <see cref="TSLanguage" /> struct.</summary>
public static unsafe partial class TSLanguageTests
{
    /// <summary>Validates that the <see cref="TSLanguage" /> struct is blittable.</summary>
    [Fact]
    public static void IsBlittableTest()
    {
        Assert.Equal(sizeof(TSLanguage), Marshal.SizeOf<TSLanguage>());
    }

    /// <summary>Validates that the <see cref="TSLanguage" /> struct has the right <see cref="LayoutKind" />.</summary>
    [Fact]
    public static void IsLayoutSequentialTest()
    {
        Assert.True(typeof(TSLanguage).IsLayoutSequential);
    }

    /// <summary>Validates that the <see cref="TSLanguage" /> struct has the correct size.</summary>
    [Fact]
    public static void SizeOfTest()
    {
        Assert.Equal(1, sizeof(TSLanguage));
    }
}

/// <summary>Provides validation of the <see cref="TSLanguage" /> struct.</summary>
public static unsafe partial class TSLanguageTests
{
    /// <summary>Validates that the <see cref="TSLanguage" /> struct is blittable.</summary>
    [Fact]
    public static void IsBlittableTest()
    {
        Assert.Equal(sizeof(TSLanguage), Marshal.SizeOf<TSLanguage>());
    }

    /// <summary>Validates that the <see cref="TSLanguage" /> struct has the right <see cref="LayoutKind" />.</summary>
    [Fact]
    public static void IsLayoutSequentialTest()
    {
        Assert.True(typeof(TSLanguage).IsLayoutSequential);
    }

    /// <summary>Validates that the <see cref="TSLanguage" /> struct has the correct size.</summary>
    [Fact]
    public static void SizeOfTest()
    {
        if (Environment.Is64BitProcess)
        {
            Assert.Equal(232, sizeof(TSLanguage));
        }
        else
        {
            Assert.Equal(136, sizeof(TSLanguage));
        }
    }
}
```

**Comment by tannergooding** [comment]
This would be getting caused by it being defined twice, yes. The easiest way to handle this is to use `rsp` files and run ClangSharp once per header, rather than by passing in multiple headers at once.

You can then `--exclude` for the header with the duplicate or invalid entry.

I can also take a look and see if I can handle this more generally, but it's not trivial due to how C headers actually produce ASTs. As you can tell from the tests, only one of the traversals is able to correctly resolve the underlying struct and therefore its correct layout/size.

**Comment by davidelettieri** [comment]
I will try with using two rsp when I get back from the holidays. Thanks for the support!

**Comment by davidelettieri** [comment]
It took me a long time to get back at this but using `--config exclude-empty-records` worked. Thanks!
