### ISSUE TITLE
Possible for --with-attribute to allow for multiple `=` in args?

### ISSUE THREAD

**Issue by kkukshtel** [dotnet/ClangSharp#469]
Hello! Trying to annotate some output functions with an additional attribute, specifically:
`UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })`
or something similar.

However, no matter what I try to pass to --with-attribute this either doesn't work because the program expects a key/value(?) or it generates the proper bindings but there is no attribute output. I also looked into the TerraFX interop rsp examples where you bind to Flags but I'm still unclear on what that's doing/why attributes need a key/value configuration when I assume they should just be copy-pasted strings, as well as what the key/value would be in my case.

**Comment by kkukshtel** [comment]
Right after typing this I figured out that the key is meant to be what you are binding the attribute to, and the value is the actual attribute. However I'm still running into issues because I have the constructor for the attribute that needs to be passed in for the array. I think it's a parsing issue re this:

https://github.com/dotnet/ClangSharp/blob/32bbe8a857ce8e723557ba50dc78b4126bf9717b/sources/ClangSharpPInvokeGenerator/Program.cs#L857

Other ways to get around it could be positional params, but the ctor for the attribute has no params so [you have to do a field assignment inline](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.unmanagedcallersonlyattribute?view=net-7.0#examples).

**Comment by tannergooding** [comment]
I'm fine with a contribution that changes this to split on the first `=` rather than only require one `=`

**Comment by kkukshtel** [comment]
Sounds great, made a PR here:

https://github.com/dotnet/ClangSharp/pull/471

**Comment by tannergooding** [comment]
Resolved with #471
