### ISSUE TITLE
3.0's SilkTouch affected by a ClangSharp upstream bug whereby test code is in XML

### ISSUE THREAD

**Issue by Perksey** [dotnet/ClangSharp#470]
Example file: [out.xml.txt](https://github.com/dotnet/Silk.NET/files/6963748/out.xml.txt)

This needs to be fixed upstream in [the ClangSharp repo](https://github.com/microsoft/ClangSharp) and the version updated in our projects once a new update is released encompassing these changes.

The likely culprit is the OutputFactoryBuilder, but don't quote me on that.

Related dotnet/Silk.NET#557

**Comment by tannergooding** [comment]
@Perksey, looks to have worked 🎉

**Comment by Perksey** [comment]
Awesome, thanks! :tada:
