### ISSUE TITLE
PInvokeGenerator test failures

### ISSUE THREAD

**Issue by Pixelstormer** [dotnet/ClangSharp#475]
I'm consistently getting the same set of test failures from a fresh clone of the repository, but I can't seem to find any preexisting issues or PRs about the test failures I'm seeing. The failures happen on the main branch, as well as on the most recent release (16.0.0).

- [`.trx` files produced by `dotnet test`](https://github.com/dotnet/ClangSharp/files/12717626/trx.tar.gz)

- [Command-line output of `dotnet test`](https://github.com/dotnet/ClangSharp/files/12717687/main.txt.gz) (Too long to inline in issue text)

From what I can tell, these tests don't actually seem to be ran on CI, which could be part of why the failures have gone seemingly unnoticed. Or, if the failures are expected, that is not documented clearly enough in the repository.

**Comment by tannergooding** [comment]
Will take a look.

All tests should be running as part of CI and should be passing.

**Comment by Pixelstormer** [comment]
I've taken another look at the CI logs, and the problem is actually that tests seem to only run on Windows, not Linux or MacOS. I'm on Linux so I originally only looked at the CI logs for Linux, and didn't spot that tests were actually being ran, just on windows and not the other platforms.
