### ISSUE TITLE
Roadmap considerations

### ISSUE THREAD

**Issue by deadlocklogic** [dotnet/ClangSharp#489]
Are you considering structuring the codebase to support `Generator`/`Pass` architecture?
Take a look at [CppSharp](https://github.com/mono/CppSharp) which is already a very similar project but with more advanced generation helper/boilerplate.
Or is this project limited to C# primarily?
Another question: how well does this project resolves types, especially member class templates etc... because `libclang` has many pitfalls overall.
I have an infrastructure for binding generation like lua/python and which I am currently porting to `CppSharp`, and might work on a `ClangSharp` backend too.
Thanks.

**Comment by tannergooding** [comment]
> Are you considering structuring the codebase to support Generator/Pass architecture?

No. ClangSharp is intentionally just bindings over libClang + some missing functionality exposed via libClangSharp. It is not designed to be a more extensible or expressive system and simply provides a surface area through which others can build their own tools

The P/Invoke Generator is then explicitly to create blittable bindings for .NET and likewise is limited to extensibility within the constraints of its design goals

> Take a look at [CppSharp](https://github.com/mono/CppSharp) which is already a very similar project but with more advanced generation helper/boilerplate.
 Or is this project limited to C# primarily?

They are different projects with different priorities/goals. They each have their own pros/cons for various scenarios.

ClangSharp is, as expressed above, simply C# bindings over Clang. The P/Invoke generator exists to provide blittable bindings over C and a very limited subset of ABI stable C++. It does not aim to support templates or other features that cannot be expressed in C#/.NET. -- Templates and generics are not compatible with eachother, for example. Likewise, macros do not have 1-to-1 translations (and aren't accurately preserved in the Clang AST).

> Another question: how well does this project resolves types, especially member class templates etc... because libclang has many pitfalls overall.

`libClangSharp` aims to fill in many of the gaps presented by `libClang` and allows better parsing of the actual C/C++ ASTs. However, many concepts do not map well outside of C++ and there are limits to what even the underlying C++ Clang APIs expose and make available. As mentioned above, macros are fundamentally lossy on many levels. Other scenarios likewise "lose" information in the Clang AST and so there are some things that are not trivially possible.

**Comment by deadlocklogic** [comment]
Thanks, I was in the course of evaluating this library.
Before I was using a C++ library [cppast](https://github.com/foonathan/cppast) also based on `libclang` and which tried to improve the limitations:
>  Parser based on libclang: While libclang does have its limitations and/or bugs, the implemented parser uses various workarounds/hacks to provide a parser that breaks only in rare edge cases you won't notice. See [issues tagged with libclang-parser for a list](https://github.com/foonathan/cppast/issues?q=is%3Aissue+is%3Aopen+label%3Alibclang-parser);

So basically this project can be viewed as a C# equivalent of the former.
