### ISSUE TITLE
Inline Arrays

### ISSUE THREAD

**Issue by kkukshtel** [dotnet/ClangSharp#495]
I was looking around the codebase and saw that there was some previous work to start supporting the new inline array attribute in dotnet 8 but then also saw it looked like it was reverted. Is the intention to support this moving forward or was there a specific reason it was removed?

**Comment by tannergooding** [comment]
> then also saw it looked like it was reverted

It wasn't removed at all, it simply requires targeting `-config preview-codegen` currently.

Once https://github.com/dotnet/ClangSharp/pull/496 is merged, it will be available via `-config latest-codegen` as well.

**Comment by kkukshtel** [comment]
Awesome, thank you!
