### ISSUE TITLE
17.0.0 not available

### ISSUE THREAD

**Issue by arhuaco** [dotnet/ClangSharp#500]
Hello there. In the documentation 17.0.0 is recommended but I cannot find it, as far as I can tell 16.0.0 is the most recent version I can install. What am I missing?

            dotnet tool install --global ClangSharpPInvokeGenerator --version 17.0.0

**Comment by tannergooding** [comment]
Publish got delayed due to the holidays. I should have it up shortly.

**Comment by tannergooding** [comment]
This was completed and is available on NuGet

A v17.0.1 with a couple minor fixes should be up later today as well
